// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdyexctnesfewmhhlfay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeWV4Y3RuZXNmZXdtaGhsZmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODcyMjgsImV4cCI6MjA2NDM2MzIyOH0.maczEKIdgUgQhNZrI62pqSW7SiGi-apFDZeRoyPVTOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);